# Generated by Django 2.2.6 on 2019-10-14 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('question_type', models.CharField(choices=[('definition', 'definition'), ('exercise', 'exercise')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('junior', 'junior'), ('min', 'mid'), ('senior', 'senior')], max_length=10)),
                ('public', models.CharField(choices=[('yes', 'yes'), ('true', 'true')], max_length=10)),
                ('group', models.ManyToManyField(to='HRQuestions.Group')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRQuestions.Language')),
            ],
        ),
    ]
