# Generated by Django 2.2.6 on 2019-10-19 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRQuestions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionGroup',
            new_name='QuestionList',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='tittle',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='public',
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
