# Generated by Django 2.2.6 on 2019-10-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRQuestions', '0004_auto_20191027_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('definition', 'definicja'), ('exercise', 'zadanie')], max_length=10, verbose_name='Typ pytania'),
        ),
        migrations.AlterField(
            model_name='questionlist',
            name='questions',
            field=models.ManyToManyField(blank=True, to='HRQuestions.Question'),
        ),
    ]
