# Generated by Django 2.2.6 on 2019-11-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRQuestions', '0006_auto_20191107_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='leader',
            new_name='recruiter',
        ),
    ]
